; PlatformIO Project Configuration File
;
;    uild options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/rojectconf.html

[env]
platform_packages =
    framework-arduinoespressif32@3.20014.231204

; ===================== NEXUS =====================
[env:NEXUS_Cabeca]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<NEXUS/Cabeca/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/adafruit/Adafruit_QMC5883P.git
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO

[env:NEXUS_musculo]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<NEXUS/musculo/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.11

[env:NEXUS_Olho]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<NEXUS/Olho/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/gamegine/HCSR04-ultrasonic-sensor-lib.git

[env:NEXUS_Pe]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<NEXUS/Pe/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

; ===================== CRONOS =====================
[env:CRONOS_Cabeca]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<CRONOS/Cabeca/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/adafruit/Adafruit_QMC5883P.git
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO

[env:CRONOS_musculo]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<CRONOS/musculo/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.11

[env:CRONOS_Olho]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<CRONOS/Olho/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/gamegine/HCSR04-ultrasonic-sensor-lib.git

[env:CRONOS_Pe]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<CRONOS/Pe/>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

; ===================== TESTES =====================
[env:teste_resposta_olho]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/resposta_olho.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:teste_resposta_pe]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/resposta_pe.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1



[env:teste_placa_olho]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/teste_placa_olho.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:teste_placa_pe]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/teste_placa_pe.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:teste_motores]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/teste_motores.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:testemuscDisplay]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/testemuscDisplay.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.11

[env:testecomunicacaoCabeca]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/testecomunicacaoCabeca.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:testeBussolaCabeca]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/testeBussolaCabeca.cpp>
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1


[env:PIDBussola]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/PIDBussola.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:blink]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/blink.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1


[env:Kicker]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/Kicker.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:descobridor_mac]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/descobridor_mac.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:espnow_teste]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<testes/espnow_teste.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
